-- Spritesheet lua file generated by TexturePacker.

local AddonName, Addon = ...

Addon.Spritesheet = {
  Path = format("Interface\\AddOns\\%s\\Assets\\Spritesheet.tga", AddonName),
  Width = 128,
  Height = 256,
  Sprites = {
    ["Arrow_Down"] = {
      Width = 25,
      Height = 25,
      Coords = {
        64 / 128, -- Left
        (64 + 25) / 128, -- Right
        96 / 256, -- Top
        (96 + 25) / 256 -- Bottom
      }
    },
    ["Arrow_Left"] = {
      Width = 25,
      Height = 25,
      Coords = {
        89 / 128, -- Left
        (89 + 25) / 128, -- Right
        96 / 256, -- Top
        (96 + 25) / 256 -- Bottom
      }
    },
    ["Arrow_Right"] = {
      Width = 25,
      Height = 25,
      Coords = {
        64 / 128, -- Left
        (64 + 25) / 128, -- Right
        121 / 256, -- Top
        (121 + 25) / 256 -- Bottom
      }
    },
    ["Arrow_Up"] = {
      Width = 25,
      Height = 25,
      Coords = {
        89 / 128, -- Left
        (89 + 25) / 128, -- Right
        121 / 256, -- Top
        (121 + 25) / 256 -- Bottom
      }
    },
    ["Checkmark"] = {
      Width = 25,
      Height = 25,
      Coords = {
        0 / 128, -- Left
        (0 + 25) / 128, -- Right
        128 / 256, -- Top
        (128 + 25) / 256 -- Bottom
      }
    },
    ["Crate_Black"] = {
      Width = 32,
      Height = 32,
      Coords = {
        0 / 128, -- Left
        (0 + 32) / 128, -- Right
        0 / 256, -- Top
        (0 + 32) / 256 -- Bottom
      }
    },
    ["Crate_Blue"] = {
      Width = 32,
      Height = 32,
      Coords = {
        32 / 128, -- Left
        (32 + 32) / 128, -- Right
        0 / 256, -- Top
        (0 + 32) / 256 -- Bottom
      }
    },
    ["Crate_Brown"] = {
      Width = 32,
      Height = 32,
      Coords = {
        64 / 128, -- Left
        (64 + 32) / 128, -- Right
        0 / 256, -- Top
        (0 + 32) / 256 -- Bottom
      }
    },
    ["Crate_Green"] = {
      Width = 32,
      Height = 32,
      Coords = {
        96 / 128, -- Left
        (96 + 32) / 128, -- Right
        0 / 256, -- Top
        (0 + 32) / 256 -- Bottom
      }
    },
    ["Crate_Grey"] = {
      Width = 32,
      Height = 32,
      Coords = {
        0 / 128, -- Left
        (0 + 32) / 128, -- Right
        32 / 256, -- Top
        (32 + 32) / 256 -- Bottom
      }
    },
    ["Crate_Red"] = {
      Width = 32,
      Height = 32,
      Coords = {
        32 / 128, -- Left
        (32 + 32) / 128, -- Right
        32 / 256, -- Top
        (32 + 32) / 256 -- Bottom
      }
    },
    ["Face"] = {
      Width = 32,
      Height = 32,
      Coords = {
        64 / 128, -- Left
        (64 + 32) / 128, -- Right
        32 / 256, -- Top
        (32 + 32) / 256 -- Bottom
      }
    },
    ["Ground"] = {
      Width = 32,
      Height = 32,
      Coords = {
        96 / 128, -- Left
        (96 + 32) / 128, -- Right
        32 / 256, -- Top
        (32 + 32) / 256 -- Bottom
      }
    },
    ["Home"] = {
      Width = 25,
      Height = 25,
      Coords = {
        25 / 128, -- Left
        (25 + 25) / 128, -- Right
        128 / 256, -- Top
        (128 + 25) / 256 -- Bottom
      }
    },
    ["Marker"] = {
      Width = 32,
      Height = 32,
      Coords = {
        0 / 128, -- Left
        (0 + 32) / 128, -- Right
        64 / 256, -- Top
        (64 + 32) / 256 -- Bottom
      }
    },
    ["Pause"] = {
      Width = 25,
      Height = 25,
      Coords = {
        50 / 128, -- Left
        (50 + 25) / 128, -- Right
        146 / 256, -- Top
        (146 + 25) / 256 -- Bottom
      }
    },
    ["Play"] = {
      Width = 25,
      Height = 25,
      Coords = {
        0 / 128, -- Left
        (0 + 25) / 128, -- Right
        153 / 256, -- Top
        (153 + 25) / 256 -- Bottom
      }
    },
    ["Player_Down"] = {
      Width = 32,
      Height = 32,
      Coords = {
        32 / 128, -- Left
        (32 + 32) / 128, -- Right
        64 / 256, -- Top
        (64 + 32) / 256 -- Bottom
      }
    },
    ["Player_Left"] = {
      Width = 32,
      Height = 32,
      Coords = {
        64 / 128, -- Left
        (64 + 32) / 128, -- Right
        64 / 256, -- Top
        (64 + 32) / 256 -- Bottom
      }
    },
    ["Player_Right"] = {
      Width = 32,
      Height = 32,
      Coords = {
        96 / 128, -- Left
        (96 + 32) / 128, -- Right
        64 / 256, -- Top
        (64 + 32) / 256 -- Bottom
      }
    },
    ["Player_Up"] = {
      Width = 32,
      Height = 32,
      Coords = {
        0 / 128, -- Left
        (0 + 32) / 128, -- Right
        96 / 256, -- Top
        (96 + 32) / 256 -- Bottom
      }
    },
    ["Question"] = {
      Width = 25,
      Height = 25,
      Coords = {
        25 / 128, -- Left
        (25 + 25) / 128, -- Right
        153 / 256, -- Top
        (153 + 25) / 256 -- Bottom
      }
    },
    ["Reset"] = {
      Width = 25,
      Height = 25,
      Coords = {
        75 / 128, -- Left
        (75 + 25) / 128, -- Right
        146 / 256, -- Top
        (146 + 25) / 256 -- Bottom
      }
    },
    ["Wall"] = {
      Width = 32,
      Height = 32,
      Coords = {
        32 / 128, -- Left
        (32 + 32) / 128, -- Right
        96 / 256, -- Top
        (96 + 32) / 256 -- Bottom
      }
    },
  }
}
