--[[
************************************************************************
esMX.lua
esMX localization strings for Collectinator
************************************************************************
File date: 2012-09-12T1:10:19Z 
File revision: 5ba9799caf14e633944aab5775e188f66ae4206a 
Project revision: 7965d53efd4d128d18e4cce83c50b11aada57da6
Project version: 8.2.5.2
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/esMX/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "esMX", false)

if not L then return end

L["Bana Wildmane"] = "Bana Ferocrín"
L["Belbi Quikswitch"] = "Belbi Tiratrastos"
L["Blix Fixwidget"] = "Blix Chirimbolo"

